services:
  unidoc-backend:
    environment:
      - BD_URL=localhost
  unidoc-frontend:
    environment:
      - VITE_BACKEND_URL=http://unidoc-backend:8080
    volumes:
      - ../../../../frontend/src:/app/src
      - ../../../../frontend/public:/app/public
      - ../../../../frontend/index.html:/app/index.html
      - ../../../../frontend/vite.config.ts:/app/vite.config.ts
      - ../../../../frontend/tsconfig.json:/app/tsconfig.json
      - ../../../../frontend/package.json:/app/package.json
  unidoc-crawler:
    environment:
      - THESIS_API_URL=http://unidoc-backend:8080/api/thesis
      - UNIVERSITY_API_URL=http://unidoc-backend:8080/api/universities