services:
  unidoc-backend:
    image: unidoc-backend
    container_name: unidoc-backend
    ports:
      - "8080:8080"
    networks:
      - unidoc-network
  unidoc-frontend:
    image: unidoc-frontend
    container_name: unidoc-frontend
    ports:
      - "5173:5173"
    networks:
      - unidoc-network
  unidoc-db:
    image: postgres:15
    container_name: unidoc-db
    restart: always
    environment:
      POSTGRES_DB: uni_doc
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./resources/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - unidoc-network
  unidoc-elasticsearch:
    image: elasticsearch:8.19.14
    container_name: unidoc-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    networks:
      - unidoc-network

volumes:
  db_data:

networks:
  unidoc-network:
    driver: bridge
