services:
  unidoc-backend:
    image: unidoc-backend
    container_name: unidoc-backend
    ports:
      - "8080:8080"
    depends_on:
      unidoc-db:
        condition: service_started
      unidoc-elasticsearch:
        condition: service_healthy
    networks:
      - unidoc-network
    healthcheck:
      test: ["CMD-SHELL", "curl --fail --silent http://localhost:8080/api/health > /dev/null"]
  unidoc-frontend:
    image: unidoc-frontend
    container_name: unidoc-frontend
    ports:
      - "5173:5173"
    networks:
      - unidoc-network
  unidoc-db:
    image: postgres:15
    container_name: unidoc-db
    restart: always
    environment:
      POSTGRES_DB: uni_doc
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./resources/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - unidoc-network
  unidoc-elasticsearch:
    image: elasticsearch:9.4.1
    container_name: unidoc-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    networks:
      - unidoc-network
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200 >/dev/null || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
  unidoc-crawler:
    image: unidoc-crawler
    container_name: unidoc-crawler
    depends_on:
      unidoc-backend:
        condition: service_healthy
      unidoc-elasticsearch:
        condition: service_healthy
    networks:
      - unidoc-network

volumes:
  db_data:
  elastic_data:

networks:
  unidoc-network:
    driver: bridge
