services:
  unidoc-backend:
    build:
      context: ../../../../backend
      dockerfile: src/main/docker/Dockerfile
    container_name: unidoc-backend
  unidoc-frontend:
    build:
      context: ../../../../frontend
      dockerfile: src/main/docker/Dockerfile
    container_name: unidoc-frontend
  unidoc-db:
    image: postgres:15
    container_name: unidoc-db
    restart: always
    environment:
      POSTGRES_DB: uni_doc
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./resources/init.sql:/docker-entrypoint-initdb.d/init.sql
  unidoc-elasticsearch:
    image: elasticsearch:8.19.14
    container_name: unidoc-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"

volumes:
  db_data: