spring.application.name=backend

# Database Configuration
db.url=jdbc:postgresql://unidoc-db:5432/uni_doc
db.user=postgres
db.password=postgres

# Elasticsearch Configuration
spring.elasticsearch.uris=http://unidoc-elasticsearch:9200
spring.elasticsearch.connection-timeout=30s
spring.elasticsearch.socket-timeout=30s

